# Chapter 3: Linear Models for Regression 线性回归模型
# 本章介绍线性回归的频率派和贝叶斯方法

name: "Linear Models for Regression"

# 3.1 线性基函数模型
linear_basis_models:
  # 基函数类型
  basis_functions:
    - "polynomial"     # 多项式基函数
    - "gaussian"       # 高斯基函数
    - "sigmoid"        # sigmoid基函数
    - "fourier"        # 傅里叶基函数
    
  # 多项式基函数配置
  polynomial:
    order: 9           # 多项式阶数
    
  # 高斯基函数配置
  gaussian_basis:
    n_basis: 9         # 基函数数量
    width: 0.1         # 基函数宽度(标准差)
    
  # 数据生成
  data_generation:
    n_train: 20        # 训练样本数
    n_test: 100        # 测试样本数
    noise_std: 0.3     # 噪声标准差
    x_min: 0
    x_max: 1
    
  # 正则化
  regularization:
    enabled: true
    lambda_values: [0, 0.001, 0.01, 0.1]

# 3.2 偏差-方差分解
bias_variance:
  # 实验配置
  n_datasets: 100      # 生成的数据集数量
  n_samples: 25        # 每个数据集的样本数
  polynomial_orders: [1, 3, 9]  # 测试的多项式阶数
  
  # 真实函数
  true_function: "sin"  # sin(2πx)
  noise_std: 0.1

# 3.3 贝叶斯线性回归
bayesian_linear_regression:
  # 先验参数
  prior:
    alpha: 2.0         # 先验精度(权重的精度)
    beta: 25.0         # 噪声精度(已知)
    
  # 基函数配置
  basis_type: "gaussian"
  n_basis: 9
  
  # 顺序学习
  sequential_learning:
    enabled: true
    data_points: [1, 2, 5, 20]  # 展示不同数据量的后验
    
  # 预测分布
  predictive_distribution:
    n_samples: 5       # 从后验采样的函数数量

# 3.4 贝叶斯模型比较
model_comparison:
  # 模型候选（不同的多项式阶数）
  model_orders: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  
  # 证据计算
  evidence_approximation:
    enabled: true
    
  # 超参数优化
  hyperparameter_optimization:
    enabled: true
    method: "marginal_likelihood"  # 最大化边际似然

# 3.5 证据近似
evidence_approximation:
  # 超参数初始值
  initial_alpha: 1.0
  initial_beta: 1.0
  
  # 优化配置
  max_iterations: 100
  tolerance: 1e-4
  
  # 可视化
  show_convergence: true

# 3.6 固定基函数的局限性
limitations:
  # 演示维度诅咒
  curse_of_dimensionality:
    dimensions: [1, 2, 5, 10]
    n_basis_per_dim: 10
    
  # 局部基函数 vs 全局基函数
  basis_comparison:
    local: ["gaussian", "spline"]
    global: ["polynomial", "fourier"]